/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.CommunityAdmin;

import Business.Ecosystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author moins
 */
public class CommunityAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommunityAdminJPanel
     */
    JPanel WorkArea;
    UserAccount useraccount;
    Ecosystem business;
    public CommunityAdminJPanel(JPanel WorkArea, UserAccount useraccount, Ecosystem business) {
        initComponents();
        this.business = business;
        this.WorkArea=WorkArea;
        this.useraccount = useraccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        communityAdminSplitPane = new javax.swing.JSplitPane();
        leftJPanel = new javax.swing.JPanel();
        rightJPanel = new javax.swing.JPanel();
        btnCommunityAdmin = new javax.swing.JButton();
        btnManageHospitals = new javax.swing.JButton();
        lblPatientPortal1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));

        leftJPanel.setBackground(new java.awt.Color(204, 255, 204));
        leftJPanel.setLayout(new java.awt.CardLayout());
        communityAdminSplitPane.setRightComponent(leftJPanel);

        rightJPanel.setBackground(new java.awt.Color(153, 255, 153));
        rightJPanel.setPreferredSize(new java.awt.Dimension(280, 840));

        btnCommunityAdmin.setBackground(new java.awt.Color(98, 203, 182));
        btnCommunityAdmin.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnCommunityAdmin.setText("Manage Community");
        btnCommunityAdmin.setPreferredSize(new java.awt.Dimension(132, 25));
        btnCommunityAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommunityAdminActionPerformed(evt);
            }
        });

        btnManageHospitals.setBackground(new java.awt.Color(98, 203, 182));
        btnManageHospitals.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnManageHospitals.setText("Manage Hospital");
        btnManageHospitals.setPreferredSize(new java.awt.Dimension(132, 25));
        btnManageHospitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageHospitalsActionPerformed(evt);
            }
        });

        lblPatientPortal1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblPatientPortal1.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientPortal1.setText("Community Portal ");

        javax.swing.GroupLayout rightJPanelLayout = new javax.swing.GroupLayout(rightJPanel);
        rightJPanel.setLayout(rightJPanelLayout);
        rightJPanelLayout.setHorizontalGroup(
            rightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightJPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(rightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnManageHospitals, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCommunityAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rightJPanelLayout.createSequentialGroup()
                        .addComponent(lblPatientPortal1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        rightJPanelLayout.setVerticalGroup(
            rightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightJPanelLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(lblPatientPortal1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCommunityAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManageHospitals, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(550, Short.MAX_VALUE))
        );

        communityAdminSplitPane.setLeftComponent(rightJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(communityAdminSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1009, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(communityAdminSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCommunityAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommunityAdminActionPerformed
        // TODO add your handling code here:

        ManageCommunityJPanel manageCommunityJPanel = new ManageCommunityJPanel(leftJPanel, business, useraccount);
        leftJPanel.add("ManageCommunity", manageCommunityJPanel);
        CardLayout layout = (CardLayout)leftJPanel.getLayout();
        layout.next(leftJPanel);
    }//GEN-LAST:event_btnCommunityAdminActionPerformed

    private void btnManageHospitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageHospitalsActionPerformed
        // TODO add your handling code here:
        ManageHospitalJPanel manageHospitalJPanel = new  ManageHospitalJPanel(leftJPanel, business, useraccount);
        leftJPanel.add("ManageHospital",  manageHospitalJPanel);
        CardLayout layout = (CardLayout)leftJPanel.getLayout();
        layout.next(leftJPanel);
    }//GEN-LAST:event_btnManageHospitalsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCommunityAdmin;
    private javax.swing.JButton btnManageHospitals;
    private javax.swing.JSplitPane communityAdminSplitPane;
    private javax.swing.JLabel lblPatientPortal1;
    private javax.swing.JPanel leftJPanel;
    private javax.swing.JPanel rightJPanel;
    // End of variables declaration//GEN-END:variables
}
