/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.CommunityAdmin;

import Business.Community.Community;
import Business.Ecosystem;
import Business.Hospital.Hospital;
import Business.Role.CommunityAdminRole;
import Business.Role.HospitalRole;
import Business.Role.SystemAdminRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author moins
 */
public class CreateCommunity extends javax.swing.JPanel {

    /**
     * Creates new form CreateCommunity
     */;
    JPanel WorkArea;
    Ecosystem business;
    UserAccount useraccount;
    public CreateCommunity(JPanel WorkArea, Ecosystem business, UserAccount useraccount) {
        initComponents();
        this.WorkArea=WorkArea;
        this.business=business;
        this.useraccount=useraccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCommunity = new javax.swing.JTextField();
        btnSaveCommunity = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblHouse = new javax.swing.JLabel();
        txtHouse = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Community:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 203, -1, -1));
        add(txtCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 200, 148, -1));

        btnSaveCommunity.setText("Save");
        btnSaveCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCommunityActionPerformed(evt);
            }
        });
        add(btnSaveCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 408, -1, -1));

        lblUsername.setText("Username:");
        add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 243, -1, -1));

        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 240, 148, -1));

        lblPassword.setText("Password:");
        add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 283, -1, -1));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 280, 148, -1));

        lblCity.setText("City:");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 326, -1, -1));

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 320, 148, -1));

        lblHouse.setText("House:");
        add(lblHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 360, -1, -1));
        add(txtHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 360, 148, -1));

        btnBack.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, 30));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CREATE COMMUNITY ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCommunityActionPerformed
        // TODO add your handling code here:
        
        Community newCommunity = new Community();
        String communityName = txtCommunity.getText();
        String UserName = txtUserName.getText();
        String Password = txtPassword.getText();
        String city = txtCity.getText();
        String house = txtHouse.getText();
        
        if(txtCommunity.getText().isEmpty()||txtUserName.getText().isEmpty()||txtPassword.getText().isEmpty()||txtCity.getText().isEmpty()||txtHouse.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter all details");
            return;
        }
        else 
            if(!communityName.matches("^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$")){
            JOptionPane.showMessageDialog(this, "Invalid Communtiy Name");
            return;
        }
        
        else 
            if(!city.matches("^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$")){
            JOptionPane.showMessageDialog(this, "Invalid City Name");
            return;
        }
        else 
            {
        newCommunity.setName(communityName);
        newCommunity.setCity(city);
        newCommunity.setHouse(house);
        
        
        Community community = business.getCommunityDirectory().addCommunity(newCommunity);
        
         JOptionPane.showMessageDialog(this,"Community Info Saved");
 
        txtCommunity.setText("");  
        txtCity.setText("");
        txtHouse.setText("");
        txtUserName.setText("");
        txtPassword.setText("");
        
        
        UserAccount account = business.getUserAccountDirectory().createUserAccount(UserName, Password, community.getCommunityId(), new CommunityAdminRole(), community);
  
            }
    }//GEN-LAST:event_btnSaveCommunityActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        WorkArea.remove(this);
        CardLayout layout = (CardLayout) WorkArea.getLayout();
        layout.previous(WorkArea);
        
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSaveCommunity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblHouse;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtHouse;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
