/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Person.AllEmployeeDetails;
import Person.PersonDetails;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author moins
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    AllEmployeeDetails employeeDetails;
    PersonDetails p; 
    
    public ViewJPanel(AllEmployeeDetails employeeDetails) {
        initComponents();
        this.employeeDetails = employeeDetails;
       
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreate = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblEmployeeId = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblStartDate = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        lblPositionTitle = new javax.swing.JLabel();
        lblCellPhoneNo = new javax.swing.JLabel();
        lblEmailId = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        txtStartDate = new javax.swing.JTextField();
        txtLevel = new javax.swing.JTextField();
        txtTeamInfo = new javax.swing.JTextField();
        txtPositionTitle = new javax.swing.JTextField();
        txtCellPhoneNo = new javax.swing.JTextField();
        txtEmployeeId = new javax.swing.JTextField();
        txtEmailId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployeeDrc = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblTeamInfo2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        CmbboxSearch = new javax.swing.JComboBox<>();
        lblImage = new javax.swing.JLabel();
        lblPhotoLocation = new javax.swing.JLabel();
        txtPhotoLocation = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 153));

        lblCreate.setBackground(new java.awt.Color(102, 255, 0));
        lblCreate.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        lblCreate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreate.setText("VIEW");
        lblCreate.setOpaque(true);

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblName.setText("Employee ID");

        lblEmployeeId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEmployeeId.setText("Name");

        lblAge.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAge.setText("Age");

        lblGender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGender.setText("Level");

        lblStartDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStartDate.setText("Gender");

        lblLevel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLevel.setText("Team Information");

        lblPositionTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPositionTitle.setText("Position Title");

        lblCellPhoneNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCellPhoneNo.setText("Cellphone No");

        lblEmailId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEmailId.setText("Email Id");

        txtStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStartDateActionPerformed(evt);
            }
        });

        txtPositionTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPositionTitleActionPerformed(evt);
            }
        });

        txtEmployeeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeIdActionPerformed(evt);
            }
        });

        tblEmployeeDrc.setBackground(new java.awt.Color(153, 255, 153));
        tblEmployeeDrc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Employee ID", "Age", "Gender", "Start Date", "Level", "Team Info", "Position Title", "Contact No", "Email", "PhotoLocation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEmployeeDrc);

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblTeamInfo2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTeamInfo2.setText("Start Date");

        lblSearch.setText("Search by");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        CmbboxSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "Employee Id", "CellPhone", "" }));
        CmbboxSearch.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                CmbboxSearchComponentShown(evt);
            }
        });
        CmbboxSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbboxSearchActionPerformed(evt);
            }
        });

        lblPhotoLocation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPhotoLocation.setText("Photo Location");

        txtPhotoLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhotoLocationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 1210, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1214, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(txtEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmployeeId)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAge)
                                    .addComponent(lblStartDate)
                                    .addComponent(lblTeamInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblName)
                                    .addComponent(lblPhotoLocation))))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhotoLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblPositionTitle)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCellPhoneNo)
                                    .addGap(66, 66, 66)
                                    .addComponent(txtCellPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(71, 71, 71)
                                    .addComponent(txtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnView)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmbboxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(lblEmployeeId))
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblGender)))
                            .addComponent(txtLevel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(txtPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblLevel)
                                                        .addComponent(txtTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(47, 47, 47))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblPositionTitle))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(lblName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblAge)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtCellPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblCellPhoneNo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblStartDate))
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblTeamInfo2)
                                            .addComponent(lblEmailId))))))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPhotoLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPhotoLocation)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnView)
                                        .addComponent(btnUpdate))
                                    .addComponent(btnDelete))))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblSearch)
                        .addGap(9, 9, 9)
                        .addComponent(CmbboxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnSearch))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPositionTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPositionTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPositionTitleActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblEmployeeDrc.getSelectedRow();

        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please Select a Row to delete");

        }else{

        DefaultTableModel model = (DefaultTableModel) tblEmployeeDrc.getModel();
        PersonDetails selectedPerson = (PersonDetails) model.getValueAt(selectedRowIndex,0);

        employeeDetails.deleteEmployee(selectedPerson);

        JOptionPane.showMessageDialog(this, "Employee Deleted");

        populateTable();
        
        txtName.setText("");
        txtEmployeeId.setText("");
        txtAge.setText("");
        txtGender.setText("");
        txtStartDate.setText("");
        txtLevel.setText("");
        txtTeamInfo.setText("");
        txtPositionTitle.setText("");
        txtCellPhoneNo.setText("");
        txtEmailId.setText("");
        txtPhotoLocation.setText("");
        lblImage.setIcon(null); 
        
        }
    }//GEN-LAST:event_btnDeleteActionPerformed
        public static int selectedRowIndex  =-1;
    
    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        
         selectedRowIndex = tblEmployeeDrc.getSelectedRow();
        if(selectedRowIndex==-1){
            JOptionPane.showMessageDialog(this, "Please Select a Row to view");
            return;
        }
        
        
        DefaultTableModel model = (DefaultTableModel) tblEmployeeDrc.getModel();
        PersonDetails selectedPerson = (PersonDetails) model.getValueAt(selectedRowIndex,0);
        
        try {
            // TODO add your handling code here:
            
            
           String photoLocation = selectedPerson.getPhotoLocation();
            lblImage.setIcon( new ImageIcon(ImageIO.read( new File( photoLocation) ) ) );
        } catch (IOException ex) {
            Logger.getLogger(ViewJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        
        

        
      
        txtName.setText(selectedPerson.getName());
        txtEmployeeId.setText(String.valueOf(selectedPerson.getEmployee_Id()) );
        txtAge.setText(String.valueOf(selectedPerson.getAge()) );
        txtGender.setText(selectedPerson.getGender());
        txtStartDate.setText(String.valueOf(selectedPerson.getStartDate()));
        txtLevel.setText(selectedPerson.getLevel());
        txtTeamInfo.setText(selectedPerson.getTeamInfo());
        txtPositionTitle.setText(selectedPerson.getPositionTitle());
        txtCellPhoneNo.setText(String.valueOf(selectedPerson.getCellPhoneNo()));
        txtEmailId.setText(selectedPerson.getEmailAddress());
        txtPhotoLocation.setText(selectedPerson.getPhotoLocation());


    }//GEN-LAST:event_btnViewActionPerformed

    private void txtEmployeeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeIdActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        
     
        
        
        String item = CmbboxSearch.getSelectedItem().toString();
        PersonDetails p = null;
        if(item.equalsIgnoreCase("Employee Id")){
            
            try {
                 p = employeeDetails.search_EmployeeById(Integer.parseInt(txtSearch.getText())); 
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Invalid Input");
                return;
            }
          
        }
        else if(item.equalsIgnoreCase("Name")){
         p = employeeDetails.search_EmployeeByName(txtSearch.getText()); 
        }
        else if(item.equalsIgnoreCase("CellPhone")){
        p = employeeDetails.search_EmployeeByCellPhoneNo(txtSearch.getText()); 
        }
        
        if(p==null){
            JOptionPane.showMessageDialog(this, "Invalid Input");
        }
        if(p!=null){
       
           
        
        txtName.setText(p.getName());
        txtEmployeeId.setText(String.valueOf(p.getEmployee_Id()) );
        txtAge.setText(String.valueOf(p.getAge()) );
        txtGender.setText(p.getGender());
        txtStartDate.setText((p.getStartDate()));
        txtLevel.setText(p.getLevel());
        txtTeamInfo.setText(p.getTeamInfo());
        txtPositionTitle.setText(p.getPositionTitle());
        txtCellPhoneNo.setText(String.valueOf(p.getCellPhoneNo()));
        txtEmailId.setText(p.getEmailAddress());
        String photoLocation = p.getPhotoLocation();
        
         try {
            // TODO add your handling code here:
            lblImage.setIcon( new ImageIcon(ImageIO.read( new File( photoLocation) ) ) );
            
          
        } catch (IOException ex) {
           Logger.getLogger(ViewJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
         
     
        
    }//GEN-LAST:event_btnSearchActionPerformed
    }
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:     

        if(selectedRowIndex==-1){
            JOptionPane.showMessageDialog(this, "Please Select a Row to update");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblEmployeeDrc.getModel();
        PersonDetails selectedPerson = (PersonDetails) model.getValueAt(selectedRowIndex,0);

          
         if (!txtName.getText().matches("^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$")) {
            JOptionPane.showMessageDialog(this, "Invalid Name");
            return;
        }else
            
            if(  Integer.parseInt(txtEmployeeId.getText())   <0 ||Integer.parseInt(txtEmployeeId.getText()) >99999){
            JOptionPane.showMessageDialog(this, "Invalid Employee Id, cannot exceed 99999");
            return;
            } 
        else
         if(Integer.parseInt(txtAge.getText()) <0 ||(Integer.parseInt(txtAge.getText()))>100){
            JOptionPane.showMessageDialog(this, "Invalid age, Limit 0-100");
            return;
        }
        else
            if(!txtGender.getText().equalsIgnoreCase("Male") && !txtGender.getText().equalsIgnoreCase("Female")){
            JOptionPane.showMessageDialog(this, "Please enter a valid Gender");
            return;
        }
        else
         if(!txtStartDate.getText().matches("^(?:(?:(?:0?[13578]|1[02])(\\/|-|\\.)31)\\1|" +
            "(?:(?:0?[1,3-9]|1[0-2])(\\/|-|\\.)(?:29|30)\\2))" +
            "(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$|^(?:0?2(\\/|-|\\.)29\\3" +
            "(?:(?:(?:1[6-9]|[2-9]\\d)?(?:0[48]|[2468][048]|" +
            "[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|" +
            "^(?:(?:0?[1-9])|(?:1[0-2]))(\\/|-|\\.)(?:0?[1-9]|1\\d|" +
            "2[0-8])\\4(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$")){
            
              JOptionPane.showMessageDialog(this, "Invalid Start Date");
              return;
        }
         else       
          if(txtLevel.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter level of Employee");
            return;
        }else
        if(txtTeamInfo.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Enter Team Information");
            return;
        }else
        if(txtPositionTitle.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter Position tile for employee");
            return;
        }else  
         
        if(!txtCellPhoneNo.getText().matches("^\\D?(\\d{3})\\D?\\D?(\\d{3})\\D?(\\d{4})$")){
             JOptionPane.showMessageDialog(this, "Invalid Cell Phone Number");
             return;
        }
        else
            
        if(!txtEmailId.getText().matches( "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*" +
            "@" + "(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$")){
            JOptionPane.showMessageDialog(this, "Invalid Email");
            return;
        }
       
        else
            
        if(!txtPhotoLocation.getText().matches("[^\\s]+(.*?)\\.(jpg|jpeg|png|gif|JPG|JPEG|PNG|GIF)$")){
        JOptionPane.showMessageDialog(this, "Please enter a valid path location");
        return;
        }
        else {
            
        selectedPerson.setName(txtName.getText());
        selectedPerson.setEmployee_Id (Integer.parseInt(txtEmployeeId.getText()));
        selectedPerson.setAge(Integer.parseInt(txtAge.getText()));
        selectedPerson.setGender(txtGender.getText());
        selectedPerson.setStartDate(txtStartDate.getText());
        selectedPerson.setLevel(txtLevel.getText());
        selectedPerson.setTeamInfo(txtTeamInfo.getText());
        selectedPerson.setPositionTitle(txtPositionTitle.getText());
        selectedPerson.setCellPhoneNo((txtCellPhoneNo.getText()));
        selectedPerson.setEmailAddress(txtEmailId.getText());
       
   
        populateTable();
        
        
        JOptionPane.showMessageDialog(this, "Information Successfully updated");
        
        txtName.setText("");
        txtEmployeeId.setText("");
        txtAge.setText("");
        txtGender.setText("");
        txtStartDate.setText("");
        txtLevel.setText("");
        txtTeamInfo.setText("");
        txtPositionTitle.setText("");
        txtCellPhoneNo.setText("");
        txtEmailId.setText("");
        txtPhotoLocation.setText("");
        lblImage.setIcon(null); 
        
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void CmbboxSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbboxSearchActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_CmbboxSearchActionPerformed

    private void CmbboxSearchComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_CmbboxSearchComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbboxSearchComponentShown

    private void txtStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartDateActionPerformed

    private void txtPhotoLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhotoLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhotoLocationActionPerformed
        
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbboxSearch;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCellPhoneNo;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblEmailId;
    private javax.swing.JLabel lblEmployeeId;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhotoLocation;
    private javax.swing.JLabel lblPositionTitle;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblTeamInfo2;
    private javax.swing.JTable tblEmployeeDrc;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCellPhoneNo;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtEmployeeId;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhotoLocation;
    private javax.swing.JTextField txtPositionTitle;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtTeamInfo;
    // End of variables declaration//GEN-END:variables

  private void populateTable(){
      
      DefaultTableModel model = (DefaultTableModel) tblEmployeeDrc.getModel();
      model.setRowCount(0);
      
      for(PersonDetails pd : employeeDetails.getEmployeeDetails()){
      
          Object[] row = new Object[11];
          row[0]=pd;
          row[1]=pd.getEmployee_Id();
          row[2]=pd.getAge();
          row[3]=pd.getGender();
          row[4]=pd.getStartDate();
          row[5]=pd.getLevel();
          row[6]=pd.getTeamInfo();
          row[7]=pd.getPositionTitle();
          row[8]=pd.getCellPhoneNo();
          row[9]=pd.getEmailAddress();
          row[10]=pd.getPhotoLocation();
      
          model.addRow(row);
      }
              
    }

}

    

