/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdmin;


import Business.Ecosystem;
import Business.Hospital.Hospital;

import Business.UserAccount.UserAccount;

import UserInterface.CommunityAdmin.CreateCommunity;
import UserInterface.HospitalAdmin.ManagePhysicianJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;
import UserInterface.HospitalAdmin.CreatePhysicianJPanel;
import UserInterface.Patient.PatientHistoryJPanel;

/**
 *
 * @author moins
 */
public class MedicalCareWorkAreaJpanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Ecosystem business;
    UserAccount account;
    Hospital hospital;
    
    /**
     * Creates new form MedicalCareWorkAreaJpanel
     */
    public MedicalCareWorkAreaJpanel(JPanel userProcessContainer, UserAccount account, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.account=account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftJPanel = new javax.swing.JPanel();
        hospitalPortalBtn = new javax.swing.JButton();
        manageDoctor = new javax.swing.JButton();
        btnCommunityAdmin = new javax.swing.JButton();
        btnPatient = new javax.swing.JButton();
        btnViewEncounters = new javax.swing.JButton();
        rightJPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setPreferredSize(new java.awt.Dimension(1800, 900));

        leftJPanel.setBackground(new java.awt.Color(153, 255, 153));
        leftJPanel.setMinimumSize(new java.awt.Dimension(280, 840));
        leftJPanel.setPreferredSize(new java.awt.Dimension(280, 840));
        leftJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hospitalPortalBtn.setBackground(new java.awt.Color(98, 203, 182));
        hospitalPortalBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        hospitalPortalBtn.setText("Manage Hospital ");
        hospitalPortalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalPortalBtnActionPerformed(evt);
            }
        });
        leftJPanel.add(hospitalPortalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 200, 40));

        manageDoctor.setBackground(new java.awt.Color(98, 203, 182));
        manageDoctor.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        manageDoctor.setText("Manage Doctor");
        manageDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDoctorActionPerformed(evt);
            }
        });
        leftJPanel.add(manageDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 200, 40));

        btnCommunityAdmin.setBackground(new java.awt.Color(98, 203, 182));
        btnCommunityAdmin.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnCommunityAdmin.setText("Manage Community");
        btnCommunityAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommunityAdminActionPerformed(evt);
            }
        });
        leftJPanel.add(btnCommunityAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 200, 40));

        btnPatient.setBackground(new java.awt.Color(98, 203, 182));
        btnPatient.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnPatient.setText("Manage Patient");
        btnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientActionPerformed(evt);
            }
        });
        leftJPanel.add(btnPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 200, 40));

        btnViewEncounters.setBackground(new java.awt.Color(98, 203, 182));
        btnViewEncounters.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnViewEncounters.setText("View Encounters");
        btnViewEncounters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEncountersActionPerformed(evt);
            }
        });
        leftJPanel.add(btnViewEncounters, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 200, 40));

        rightJPanel.setBackground(new java.awt.Color(204, 255, 204));
        rightJPanel.setPreferredSize(new java.awt.Dimension(1058, 840));
        rightJPanel.setLayout(new java.awt.CardLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/SystemAdmin/one.jpg"))); // NOI18N
        rightJPanel.add(jLabel2, "card2");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WELCOME SYSTEM ADMIN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rightJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1043, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hospitalPortalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalPortalBtnActionPerformed
        // TODO add your handling code here:
        System.out.println("Testt  "+business.toString());
        SystemAdminHospitalPortalJPanel systemAdminHospitalPortalJPanel = new SystemAdminHospitalPortalJPanel(rightJPanel, business, account);
        rightJPanel.add("SystemAdminHospitalPortalJPanel", systemAdminHospitalPortalJPanel);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
        
    }//GEN-LAST:event_hospitalPortalBtnActionPerformed

    private void manageDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDoctorActionPerformed
        // TODO add your handling code here:
        ManageDoctorJPanel manageDoctorJPanel = new ManageDoctorJPanel(rightJPanel, business);
        rightJPanel.add("createDoctorJPanel", manageDoctorJPanel);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_manageDoctorActionPerformed

    private void btnCommunityAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommunityAdminActionPerformed
        // TODO add your handling code here:
        SystemAdminManageCommunityJPanel sysAdminManageComm = new SystemAdminManageCommunityJPanel(rightJPanel, business, account);
        rightJPanel.add("ManageCommunity", sysAdminManageComm);
        CardLayout layout = (CardLayout)rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_btnCommunityAdminActionPerformed

    private void btnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientActionPerformed
        // TODO add your handling code here:
        SystemAdminPatientPortalJPanel managePatientJPanel = new SystemAdminPatientPortalJPanel(rightJPanel, business);
        rightJPanel.add("CreateCommunity", managePatientJPanel);
        CardLayout layout = (CardLayout)rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_btnPatientActionPerformed

    private void btnViewEncountersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEncountersActionPerformed
        // TODO add your handling code here:
        SystemAdminEncounterHistoryJPanel adminEncounterHistoryJPanel = new SystemAdminEncounterHistoryJPanel(rightJPanel, business,account);
        rightJPanel.add("patientHistory", adminEncounterHistoryJPanel);
        CardLayout layout = (CardLayout)rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_btnViewEncountersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCommunityAdmin;
    private javax.swing.JButton btnPatient;
    private javax.swing.JButton btnViewEncounters;
    private javax.swing.JButton hospitalPortalBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel leftJPanel;
    private javax.swing.JButton manageDoctor;
    private javax.swing.JPanel rightJPanel;
    // End of variables declaration//GEN-END:variables
}
